const handler = require('serve-handler');
const http = require('http');

// Returns a promise that resolves as soon as server starts listening
// (or resolves immediately if the server is already running)
exports.getURL = () => {
  return new Promise(resolve => {
    server.listening
      ? resolve(url())
      : server.listen(() => { resolve(url())});
  });
}

exports.close = () => {
  server.close();
}

// FIXME: it should point to the actual library artifact under test
// for now there should be some h1 tag generated by `serve-handler`,
// that's all (only enough for smoke tests as I roll out these e2e tests).
const server = http.createServer((req, res) => {
  handler(req, res, {
    cleanUrls: true,
    public: 'docs'
  })
});

function url() {
  return server.address() === null
    ? null
    // had to use localhost instead of ${server.address().address},
    // because curl http://:::61146 doesn't work
    : `http://localhost:${server.address().port}`;
}